name: Frontend CI/CD
on:
  push:
    branches: [ main ]
    paths: 
      - './much-to-do/Client'
      - '.github/workflows/frontend-ci-cd.yml'

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1      

      - name: Install Dependencies
        working-directory: ./much-to-do/Client
        run: npm ci
        
      - name: Run Security Audit
        working-directory: ./much-to-do/Client
        # Adding '|| true' allows the pipeline to continue even if vulnerabilities are found
        run: npm audit --audit-level=high || true 

      - name: Build
        working-directory: ./much-to-do/Client
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.REACT_APP_API_URL }}

      - name: Deploy Frontend Script
        run: |
          chmod +x ./scripts/deploy-frontend.sh
          ./scripts/deploy-frontend.sh ${{ secrets.TF_VAR_FRONTEND_BUCKET_NAME }} ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
    
